{% set commit = "1f6857cac8ce196dae41120820cfa5e944b1f2d8" %}
{% set version = "0.2.0" %}

package:
  name: python-symengine
  version: {{ version }}

source:
  fn: {{ commit }}.tar.gz
  url: https://github.com/symengine/symengine.py/archive/{{ commit }}.tar.gz

build:
  number: 0
  skip: true        # [win and not py35]
  features:
    - vc14          # [win and py35]

requirements:
  build:
    - toolchain
    - cmake
    - symengine     0.2.0
    - python
    - cython 0.23*
    - setuptools
  run:
    - symengine     0.2.0
    - python

test:
  requires:
    - pytest
    - sympy
  imports:
    - symengine
  commands:
    - python -c $'import symengine;\nif not symengine.test():\n raise Exception("Tests failed")'    # [unix]

about:
  home: https://github.com/symengine/symengine.py
  license: MIT
  summary: 'Python wrappers for SymEngine, a fast symbolic manipulation library, written in C++'

extra:
  recipe-maintainers:
    - isuruf
    - certik
