# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "EB+IBNBOef385Fj+eZM+pjdOmJY1aXmUT9+tdATRO/+cJkF5IRN+vjL4CY4UPBSmWagTjADaB2ek+p2jvbEU2Z50/hCvIBnEnJzByx2NnDkLlBcj1bZtzk0yp9NZ1A5JrkXx+qsIegSSOGHFYMqlVilf0j5DVnBOCy2sE3QUm0RaN23xs+QbO4wzvBSHSEyN67P7zkml40pqynOp2g6W2X/L6de/3y3mMBOsQZWdZtfrTki3bVBX+nM6rb73an8cvy1pL4hbMy2ODULVooOZgIaRcBUlylCb+m8ZcbzaO6orF7j4dFFB1O/Nz8fNRI0wA8ieX6dQTeU1E7T9ciEfDUx1kh1UXxsST97cdAFayBBn9ppWCLhIJu5WfatRBsnEt49hENdvB3PHXl2jp7Ok93DWoICFSayqwZqab6C9LQt0xWoK/4IaV4xEyKt/iK0gy7F1r3ggFxhXQRLb/u8rnWorcD3JJolGVLF0l1nS9t/Rizqk6dLNLUxLGfkjp+vXHQ/N+RWmw3FKrBHUfBxTX61hENPD3DYIcuL+fDM6h0pdzMTOVwwyapYSvx6IbhurUp7rcj0jarojBpQ8BOwVUqN2LvfIv1Q6CcAj9NWEblgMzwulWUfVUW7/kCophrN3bP63BFiQcPZn85/WkHo3x7vCj6X93oi4Cjm/Dw91tEc="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --add channels symengine
      conda config --add channels symengine/label/dev
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe symengine --channel=dev
